application: minecraft-ly
version: 1
runtime: php55
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /(.+\.php)$
  script: \1
- url: /.*
  script: public/index.php
  secure: optional